apiVersion: v1
kind: Service
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  type: NodePort
  ports:
    - port: 8080
        nodePort: 30000
  selector:
    app: jenkins
status:
  loadBalancer: {}
