apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: swagger-spring-example
  name: swagger-spring-example
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: swagger-spring-example
    spec:
      containers:
      - image: my_docker_reposetory/swagger-spring-example:1.0.0
        name: swagger-spring-example
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
