apiVersion: v1
kind: Service
metadata:
  labels:
    app: swagger-spring-example
  name: swagger-spring-example
spec:
  type: NodePort
  ports:
    - port: 8080
      nodePort: 30000
  selector:
    app: swagger-spring-example
status:
  loadBalancer: {}
