apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: jenkins
    spec:
      containers:
      - image: alogo53/jenkins
        name: jenkins
#         volumeDevices
        volumeMounts: 
        - name: /var/run/docker.sock
          mountPath: /var/run/docker.sock     
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
