apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: jenkins
  name: jenkins
spec:
  replicas: 1
  strategy: {}
  template:
    metadata:
      labels:
        app: sjenkins
    spec:
      containers:
      - image: alogo53/jenkins
        name: jenkins
        ports:
        - containerPort: 8080
        resources: {}
      restartPolicy: Always
status: {}
