apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: swagger-spring-example
  name: swagger-spring-example
spec:
  externalTrafficPolicy: Cluster
  ports:
  - nodePort: 30000
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: swagger-spring-example
  sessionAffinity: None
  type: NodePort
status:
  loadBalancer: {}
